# https://toolkit.site/format.html

####################################
# PASSION
###########

[passion]
    [[passion.question]]
        question = "What are your 3 favourite topics to discuss? What could you talk about for hours on end?"
    [[passion.question]]
        question = "What things in life really make you feel free?"
    [[passion.question]]
        question = "Let 5 people who love and know you best tell you that you would be amazing at doing for a living."
    [[passion.question]]
        question = "What naturally flows for you without you even having to try?"
    [[passion.question]]
        question = "If you were to wake up tomorrow feeling truly free and happily excited about your day ahead, what  would you be off to do?"
    [[passion.question]]
        question = "You are totally ‘in your element’ and time seems to have disappeared. What are you doing?"
    [[passion.question]]
        question = "It is your birthday and somebody buys you an annual magazine subscription. Which type would you love it to be?"
    [[passion.question]]
        question = "What areas of life are you naturally drawn to?"
    [[passion.question]]
        question = "What do people ask you for information/advice about? Which areas are you deemed to be a little fountain of knowledge?"
    [[passion.question]]
        question = "If you were to pioneer a cause around the world, and it was guaranteed to be a success, what would it be?"
    [[passion.question]]
        question = "What do you love to do when you have free time and what is it that gives you that real buzz of excitement?"
    [[passion.question]]
        question = "What topics interest you and what would you really love to know lots more about?"
    [[passion.question]]
        question = "You love helping people with these 3 different things. What are they?"
    [[passion.question]]
        question = "What interests or hobbies have you had in the past few years that intrigue you and might hold the potential for a life passion?"
    [[passion.question]]
        question = "What would be hard for you to give up?"

#########################################3
# PEOPLE ID
################

[people_id]
    [[people_id.question]]
        question = "5 people that inspire you most in the world stand before you. Who are they and what is it about them that sparks something within you?"
    [[people_id.question]]
        question = "Who is someone in your life or in history whose life and work inspires and excites you? Why?"
    [[people_id.question]]
        question = "Who influenced your life most and why?"
    [[people_id.question]]
        question = "With which character in a book or movie did you relate well and why?"
    [[people_id.question]]
        question = "Which super hero was you favourite when you were small? What can that say about you?"

#########################################
# DREAMS
##############

[dreams]
    [[dreams.question]]
        question = "When you were a child, what did you always dream of doing when you got older? What do they symbolise?"
    [[dreams.question]]
        question = "What are some childhood dreams or interests you were never able to fully explore but still find intriguing?"
    [[dreams.question]]
        question = "What difference do you want to make in the world? What legacy would you like to leave behind?"
    [[dreams.question]]
        question = "You inherit R100 million, how would it change your life? What would you do with your days?"
    [[dreams.question]]
        question = "When you are dead and gone, what would you like people to say about the way you lived your life?"
    [[dreams.question]]
        question = "What careers do you have wild dreams of having?"
    [[dreams.question]]
        question = "If someone were to pay all of your living costs and expenses for 2 years, what work would you pursue in that time?"
    [[dreams.question]]
        question = "If you were to change 3 things in the world for the greater good, what would they be?"
    [[dreams.question]]
        question = "What is it that you would regret not doing with your life, if you were to die tomorrow?"
    [[dreams.question]]
        question = "What piece of knowledge do you feel as though you would love to share with the world?"
    [[dreams.question]]
        question = "The person that loves you most in the whole world asks you what you need to be doing with your life in order to be really happy. How do you respond?"
    [[dreams.question]]
        question = "If you had 5 years left to live, what would you do?"
    [[dreams.question]]
        question = "How have your fears and limiting beliefs held you back from finding or pursuing your passion in the past?"
    [[dreams.question]]
        question = "Are there any people in your life preventing you from pursuing your passion? Who are they and how are they holding you back?"
    [[dreams.question]]
        question = "What is something (or several things) you’d really like to achieve before you die?"

#########################################
# VALUES
##########################

[values]
    [[values.question]]
        question = "What are your top  most deeply held core values?"
    [[values.question]]
        question = "How does your life currently support or reflect those values?"
    [[values.question]]
        question = "Which of your top values are you ignoring or not giving enough attention?"
    [[values.question]]
        question = "What values will you never compromise?"
    [[values.question]]
        question = "Which jobs would encompass your core values?"

#########################################
# SPOKEN WORDS
#######################

[spoken_words]
    [[spoken_words.question]]
        question = "Things people say about you has a big impact on your life and often reveal a lot more than you think...\nFill these commonly spoken words below"
    [[spoken_words.question]]
        question = "Now summarise the central themes from your answer and type them below"

####################################
# SKILLS
###########

[skills]
    [[skills.question]]
        question = "Administration"
    [[skills.question]]
        question = "Analyse"
    [[skills.question]]
        question = "Artistic"
    [[skills.question]]
        question = "Communicate"
    [[skills.question]]
        question = "Computers"
    [[skills.question]]
        question = "Control"
    [[skills.question]]
        question = "Counseling"
    [[skills.question]]
        question = "Creative"
    [[skills.question]]
        question = "Devision Making"
    [[skills.question]]
        question = "Empathy"
    [[skills.question]]
        question = "Entertaining"
    [[skills.question]]
        question = "Handwork"
    [[skills.question]]
        question = "Marketing"
    [[skills.question]]
        question = "Negotiate"
    [[skills.question]]
        question = "Numeracy"
    [[skills.question]]
        question = "Objectivity"
    [[skills.question]]
        question = "Organise"
    [[skills.question]]
        question = "Planning"
    [[skills.question]]
        question = "Playing Musical Instruments"
    [[skills.question]]
        question = "Practical"
    [[skills.question]]
        question = "Public Speaking"
    [[skills.question]]
        question = "Receptive for people"
    [[skills.question]]
        question = "Sharing"
    [[skills.question]]
        question = "Sport"
    [[skills.question]]
        question = "Strategic Planning"
    [[skills.question]]
        question = "Study"
    [[skills.question]]
        question = "Taking the lead"
    [[skills.question]]
        question = "Teaching"
    [[skills.question]]
        question = "Writing"

####################################
# LIFE KEYS
#############

[life_keys]

  [[life_keys.type]]
  title = "The Artistic Type: \"Let’s create!\""
  characteristics = [
    "They are the original type",
    "They like to do things differently",
    "They do not conform to others easily",
    "They are free-spirited",
    "They are creative and therefore love to do things innovatively",
    "They are artistic",
    "They are musical"
  ]
  work_environments = [
    "They seek careers where less structure is needed",
    "They want to give expression to their creative side",
    "Suitable work environments might include law firms, museums, libraries, galleries, interior design consultancies or advertising agencies"
  ]
  things_they_love_to_do = [
    "Acting",
    "Writing or reporting",
    "Express themselves through music",
    "Creative problem solving",
    "Creative expression through colour",
    "Sculpting / photography / graphic arts / painting / interior decorating",
    "They are good at using and may have an interest in languages"
  ]

  [[life_keys.type]]
  title = "The Conventional Type: \"Let’s be dependable!\""
  characteristics = [
    "They are the practical type",
    "They like to do things in a pragmatic and methodical fashion",
    "They are highly efficient in what they do",
    "They like it when things happen in an orderly fashion",
    "They like structure",
    "They show great attention to detail"
  ]
  work_environments = [
    "They seek careers where structure, schedules and routine is demanded",
    "They want to handle data and give attention to detail",
    "Suitable work environments might include accounting, office management, data processing, working with money or numbers"
  ]
  things_they_love_to_do = [
    "Organising",
    "Appraising or evaluating",
    "Attending to detail",
    "Managing time & setting priorities",
    "Calculating & expressing their mathematical skills",
    "Systematising",
    "Taking responsibility "
  ]

  [[life_keys.type]]
  title = "The Realistic Type: \"Let’s roll up our sleeves and get the job done!\""
  characteristics = [
    "They are the outdoor type",
    "They tend to be athletic and loves to participate in sport",
    "They like to do things with their hands",
    "They are highly efficient with mechanical activities",
    "They may appear to be ‘loners’",
    "They like small groups of people"
  ]
  work_environments = [
    "They seek careers where they can be hands-on",
    "They want to handle things or objects rather than people or ideas",
    "They seek out careers which allow them to use their motor skills",
    "Suitable work environments might include agriculture, engineering, construction, maintenance or any job where they can use tools"
  ]
  things_they_love_to_do = [
    "Mechanical things",
    "Operating (heavy) equipment",
    "Driving or piloting",
    "Building mechanical/structural devices",
    "Sport or activities where they can use their ‘ball sense’",
    "Organising supplies or implements",
    "Taking physical risks"
  ]

  [[life_keys.type]]
  title = "The Investigative Type: \"Let’s figure this out!\""
  characteristics = [
    "They are the curious type",
    "They tend to be rational and analytical",
    "They like intellectual pursuits",
    "They like it if things make logically sense",
    "They are introspective by nature",
    "They may appear to be ‘loners’",
    "They like small groups of people"
  ]
  work_environments = [
    "They seek careers where they can do research or gather information",
    "They want to work with ideas rather than with people",
    "They seek out careers where they can expand their knowledge",
    "Suitable work environments might include sciences, higher education, theoretical areas of business, strategic planning"
  ]
  things_they_love_to_do = [
    "Inventing",
    "Researching",
    "Conceptualising & theorising",
    "Working independently",
    "Solving complex problems",
    "Working with computers",
    "Compiling information"
  ]

  [[life_keys.type]]
  title = "The Social Type: \"Let’s work together!\""
  characteristics = [
    "They are the helpful type",
    "They tend to be cooperative",
    "They like to make peace and build bridges",
    "They are very understanding",
    "They are people oriented",
    "They may appear to be extroverted",
    "They like different groups of people"
  ]
  work_environments = [
    "They seek careers where they can serve others",
    "They want to work with people rather than with ideas or things",
    "They seek out careers where they can solve problems through synergy",
    "Suitable work environments might include schools, churches, social services, health organisations, the people side of business"
  ]
  things_they_love_to_do = [
    "Teaching",
    "Listening and facilitating",
    "Understanding or counseling others",
    "Serving others",
    "Evaluating people’s characters",
    "Showing empathy and tact",
    "Working with others"
  ]

  [[life_keys.type]]
  title = "The Enterprising Type: \"Let’s get going!\""
  characteristics = [
    "They are the persuasive type",
    "They tend to be self confident",
    "They like to express themselves verbally",
    "They like to take risks",
    "They often gravitate towards leadership",
    "They may appear to be extroverted",
    "They enjoy to interact with people"
  ]
  work_environments = [
    "They seek careers where they can promote, market and sell",
    "They want to be in leadership positions",
    "They seek out careers where they can make money",
    "Suitable work environments might include sales, marketing, government positions, brokerage (real estate, travel), fundraising"
  ]
  things_they_love_to_do = [
    "Public speaking",
    "Selling",
    "Persuading",
    "Negotiating",
    "To be in leadership",
    "Management",
    "Taking constructive action",
    "Adventurous activities"
  ]
