[passion]
    [[passion.question]]
        question = "What are your 3 favourite topics to discuss? What could you talk about for hours on end?"
    [[passion.question]]
        question = "What things in life really make you feel free?"
    [[passion.question]]
        question = "Let 5 people who love and know you best tell you that you would be amazing at doing for a living."
    [[passion.question]]
        question = "What naturally flows for you without you even having to try?"
    [[passion.question]]
        question = "If you were to wake up tomorrow feeling truly free and happily excited about your day ahead what  would you be off to do?"
    [[passion.question]]
        question = "You are totally ‘in your element’ and time seems to have disappeared. What are you doing?"
    [[passion.question]]
        question = "It is your birthday and somebody buys you an annual magazine subscription. Which type would you love it to be?"
    [[passion.question]]
        question = "What areas of life are you naturally drawn to?"
    [[passion.question]]
        question = "What do people ask you for information/advice about? Which areas are you deemed to be a little fountain of knowledge?"
    [[passion.question]]
        question = "If you were to pioneer a cause around the world and it was guaranteed to be a success what would it be?"
    [[passion.question]]
        question = "What do you love to do when you have free time and what is it that gives you that real buzz of excitement?"
    [[passion.question]]
        question = "What topics interest you and what would you really love to know lots more about?"
    [[passion.question]]
        question = "You love helping people with these 3 different things. What are they?"
    [[passion.question]]
        question = "What interests or hobbies have you had in the past few years that intrigue you and might hold the potential for a life passion?"
    [[passion.question]]
        question = "What would be hard for you to give up?"
